"""Continuous Intraday Electricity Market Simulation.

Simulates a continuous intraday market where orders arrive over time,
are matched against the existing order book, and execute trades when
buy/sell prices overlap.

This is a price-driven continuous matching engine — no auction,
no discrete clearing. Useful for understanding market microstructure
and the liquidity dynamics of European intraday power markets
(XBID/SPOT continuous).
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# OrderBook
# ---------------------------------------------------------------------------

class OrderBook:
    """A simple price-time priority order book for intraday electricity.

    Maintains separate lists for buy (bids) and sell (asks) orders.
    Orders are matched as they arrive: a new buy order scans asks from
    cheapest upward; a new sell order scans bids from highest downward.
    The passive (standing) order's price determines the trade price.

    Parameters
    ----------
    verbose : bool
        Print matching details to stdout.
    """

    def __init__(self, verbose: bool = False) -> None:
        self._bids: list[dict] = []   # buy orders: sorted by price DESC
        self._asks: list[dict] = []   # sell orders: sorted by price ASC
        self._order_counter: int = 0
        self.verbose = verbose

    # -- public API --------------------------------------------------------

    def add(self, order: dict) -> list[dict]:
        """Add an order to the book, matching immediately where possible.

        Parameters
        ----------
        order : dict
            Keys: ``time``, ``type`` ('buy'/'sell'), ``price``, ``qty``.
            An ``_id`` key is added for tracking.

        Returns
        -------
        list[dict]
            Trades generated by matching this order.
        """
        self._order_counter += 1
        order["_id"] = self._order_counter
        trades = self._match(order)
        if order["qty"] > 0:
            self._insert(order)
        return trades

    def get_depth(self) -> dict:
        """Return a snapshot of current market depth.

        Returns
        -------
        dict
            ``{"bids": [...], "asks": [...]}`` with each side sorted
            best-to-worst (bids: descending price, asks: ascending).
        """
        return {
            "bids": sorted(self._bids, key=lambda o: -o["price"]),
            "asks": sorted(self._asks, key=lambda o: o["price"]),
        }

    # -- internals ---------------------------------------------------------

    def _match(self, order: dict) -> list[dict]:
        """Attempt to match *order* against the opposite side of the book.

        Matching rules (price-time priority):
        - A **buy** order matches the cheapest asks where ask.price <= buy.price.
        - A **sell** order matches the highest bids where bid.price >= sell.price.
        - Trade price = the passive (standing) order's price.
        - Partial fills: leftover quantity stays active and may match
          additional resting orders or (if exhausted) be inserted into the book.
        """
        trades: list[dict] = []
        if order["type"] == "buy":
            # Sort asks by price ascending (cheapest first)
            self._asks.sort(key=lambda o: o["price"])
            while order["qty"] > 0 and self._asks and self._asks[0]["price"] <= order["price"]:
                trades.extend(self._execute_trade(order, self._asks[0]))
        else:  # sell
            # Sort bids by price descending (highest first)
            self._bids.sort(key=lambda o: -o["price"])
            while order["qty"] > 0 and self._bids and self._bids[0]["price"] >= order["price"]:
                trades.extend(self._execute_trade(self._bids[0], order))
        return trades

    def _execute_trade(self, buy: dict, sell: dict) -> list[dict]:
        """Execute a trade between *buy* and *sell*, handling partial fills.

        The passive order's price determines the trade price.  If the
        passive order has more quantity than needed, the remainder
        stays in the book.  If the aggressive order has more, the
        remainder continues matching.

        Returns a single-element list with the trade record, or empty
        list if no quantity can be traded.
        """
        trade_qty = min(buy["qty"], sell["qty"])
        if trade_qty <= 0:
            return []

        # Determine which order is passive (already in book)
        # A buy in _bids or a sell in _asks is passive.
        buy_passive  = buy in self._bids
        sell_passive = sell in self._asks

        if buy_passive:
            trade_price = buy["price"]
        elif sell_passive:
            trade_price = sell["price"]
        else:
            # Both aggressive (shouldn't happen in current design)
            trade_price = (buy["price"] + sell["price"]) / 2

        # Use the later timestamp as the trade time
        trade_time = max(buy["time"], sell["time"])

        trade = {
            "time":     trade_time,
            "price":    trade_price,
            "qty":      trade_qty,
            "buy_id":   buy["_id"],
            "sell_id":  sell["_id"],
        }
        buy["qty"]  -= trade_qty
        sell["qty"] -= trade_qty

        # Remove fully-filled orders from the book
        if buy["qty"] <= 0 and buy in self._bids:
            self._bids.remove(buy)
        if sell["qty"] <= 0 and sell in self._asks:
            self._asks.remove(sell)

        if self.verbose:
            tag = "PASSIVE-BUY" if buy_passive else "PASSIVE-SELL" if sell_passive else "CROSS"
            print(f"  TRADE {tag} │ time={trade_time:.2f}  price={trade_price:.1f}  "
                  f"qty={trade_qty:.1f}  (buy#{buy['_id']} × sell#{sell['_id']})")

        return [trade]

    def _insert(self, order: dict) -> None:
        """Insert an unmatched (or partially filled) order into the book."""
        if order["type"] == "buy":
            self._bids.append(order)
        else:
            self._asks.append(order)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def simulate_intraday(orders: list[dict], verbose: bool = False) -> dict:
    """Simulate a continuous intraday electricity market.

    Parameters
    ----------
    orders : list[dict]
        Each dict must contain:
        - ``time`` (float): arrival time (e.g. hours from market open).
        - ``type`` (str): ``'buy'`` or ``'sell'``.
        - ``price`` (float): limit price in €/MWh.
        - ``qty`` (float): quantity in MW.

        Orders are assumed to be sorted by ``time`` ascending.
    verbose : bool
        Print matching details to stdout.

    Returns
    -------
    dict
        ``status``: ``"completed"`` (or ``"empty"`` if no orders).
        ``trades``: list of trade records ``{time, price, qty, buy_id, sell_id}``.
        ``vwap``: volume-weighted average price (float, or 0 if no volume).
        ``total_volume``: total MW traded.
        ``unfilled_orders``: list of orders still in the book at end of session.
    """
    if not orders:
        return {
            "status": "empty",
            "trades": [],
            "vwap": 0.0,
            "total_volume": 0.0,
            "unfilled_orders": [],
        }

    book = OrderBook(verbose=verbose)
    all_trades: list[dict] = []

    for i, order in enumerate(orders):
        # Work on a copy so original is not mutated
        o = dict(order)
        o.setdefault("_id", i + 1)
        o["qty"] = float(o["qty"])
        o["price"] = float(o["price"])

        if verbose:
            side = "BUY " if o["type"] == "buy" else "SELL"
            print(f"t={o['time']:.2f}  {side}  price={o['price']:.1f}  qty={o['qty']:.1f}")

        trades = book.add(o)
        all_trades.extend(trades)

    # Compute VWAP
    total_volume = sum(t["qty"] for t in all_trades)
    if total_volume > 0:
        vwap = sum(t["price"] * t["qty"] for t in all_trades) / total_volume
    else:
        vwap = 0.0

    # Remaining orders in book
    depth = book.get_depth()
    unfilled = depth["bids"] + depth["asks"]
    # Strip internal book markers for clean output
    clean_unfilled = [
        {k: v for k, v in o.items() if not k.startswith("_")}
        for o in unfilled
    ]

    return {
        "status": "completed",
        "trades": all_trades,
        "vwap": round(vwap, 4),
        "total_volume": total_volume,
        "unfilled_orders": clean_unfilled,
    }


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

def demo_intraday() -> dict:
    """Run a demonstration of the intraday market simulation.

    20 orders arrive over a 4-hour window (08:00 – 12:00).  The mix
    includes both buy and sell orders at realistic price levels.
    Some orders match immediately; others rest in the book.

    Returns
    -------
    dict
        Result from :func:`simulate_intraday`.
    """
    orders: list[dict] = [
        # Hour 08:xx — early morning
        {"time": 0.00, "type": "sell", "price": 50, "qty": 10},
        {"time": 0.15, "type": "sell", "price": 55, "qty": 15},
        {"time": 0.30, "type": "buy",  "price": 60, "qty": 8},
        {"time": 0.50, "type": "buy",  "price": 52, "qty": 12},
        {"time": 0.55, "type": "sell", "price": 45, "qty": 20},

        # Hour 09:xx — mid-morning
        {"time": 1.00, "type": "buy",  "price": 48, "qty": 10},
        {"time": 1.20, "type": "sell", "price": 50, "qty": 5},
        {"time": 1.40, "type": "buy",  "price": 55, "qty": 15},
        {"time": 1.60, "type": "sell", "price": 65, "qty": 10},
        {"time": 1.80, "type": "buy",  "price": 62, "qty": 10},

        # Hour 10:xx — mid-day
        {"time": 2.00, "type": "sell", "price": 70, "qty": 8},
        {"time": 2.20, "type": "buy",  "price": 72, "qty": 8},
        {"time": 2.50, "type": "sell", "price": 68, "qty": 12},
        {"time": 2.70, "type": "buy",  "price": 69, "qty": 12},

        # Hour 11:xx — late morning
        {"time": 3.00, "type": "sell", "price": 75, "qty": 20},
        {"time": 3.30, "type": "buy",  "price": 74, "qty": 15},
        {"time": 3.50, "type": "sell", "price": 73, "qty": 10},
        {"time": 3.70, "type": "buy",  "price": 76, "qty": 20},
        {"time": 3.85, "type": "sell", "price": 78, "qty": 8},
        {"time": 3.95, "type": "buy",  "price": 77, "qty": 8},
    ]

    return simulate_intraday(orders, verbose=False)
